### ISSUE TITLE
Web.Frank - Page never found

### ISSUE THREAD

**Issue by nd2s** [alevy/simple#16]
Maybe I am misunderstanding something, but with `simple-0.11.0`, `warp-3.1.12` and following code:

    run 3000 $ controllerApp () $ get "/" (return $ okHtml "success")

http://localhost:3000/ always returns error 404. Using `response` from `Web.Simple` works fine, but I can't get it working with `Frank`.

**Comment by alevy** [comment]
You need to use `respond` instead of `return`:

```haskell
run 3000 $ controllerApp () $ get "/" (respond $ okHtml "success")
```

The basic idea of any block of `Controller` code (`Frank` is just a library for the `Controller` monad), is that it either invokes `respond` (in which case the rest of the computation is not executed and an HTTP response is generated), or it `return`s, in which case the value of the block is taken from the argument to `return`.

If the top-level `Controller` `return`s, the default response is a 404.

So what you're seeing is just the default response, because your top-level controller `return`s rather than `respond`s

**Comment by nd2s** [comment]
Ah, makes sense, and works. Thanks for the explanation!

But then the example in the documentation [here](https://hackage.haskell.org/package/simple-0.11.0/docs/Web-Frank.html) seems to be wrong.

**Comment by alevy** [comment]
Yes! That's wrong... thanks for pointing it out!
